# Generated by Django 5.1.3 on 2024-12-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='weekly',
            field=models.BooleanField(default=False),
        ),
    ]
