# Generated by Django 5.1.3 on 2024-12-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(choices=[('open_mic', 'Open Mic/Karaoke'), ('none', 'Other')], default='none', max_length=20),
        ),
    ]
