# Generated by Django 5.1.4 on 2024-12-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAccount',
        ),
    ]
